site_name: Compiladores 1 Grupo 09
site_description: Documentação do projeto

theme:
  name: material

nav:
  - Home: index.md

  - Analisador Léxico:
      - Introdução: analisador_léxico/introdução.md
      - Fundamentação: analisador_léxico/fundamentação.md
      - Palavras Reservadas: analisador_léxico/palavrasreservadas.md
  - Analisador Sintático:
      - Integração Léxico-Sintático: analisador_sintatico/integracao_lexico_sintatico.md
      - Especificação da Gramática da Linguagem: analisador_sintatico/especificacao_gramatica.md
  - Testes:
      - Visão Geral: testes/visao_geral.md
      - Analisador Léxico: testes/testes_lexico.md
      - Analisador Sintático: testes/testes_sintatico.md
  - Manuais:
      - Instalação Flex e Bison: manuais/instalacao_flex_bison.md
      - Instrução Build Flex/Bison: manuais/instrucao_build_flex_bison.md
      - Makefile: manuais/makefile.md
      - Padrões de Commit: manuais/padrao_commit.md
      - Padrões de Branch: manuais/padrao_branch.md
